CREATE DATABASE IF NOT EXISTS server;
USE server;
CREATE TABLE IF NOT EXISTS SUBSCRIPTIONS(
ID int AUTO_INCREMENT NOT NULL,
Name VARCHAR(255) NOT NULL,
SubLink VARCHAR(255) NOT NULL,
PRIMARY KEY (ID)
);
CREATE TABLE IF NOT EXISTS RESULT(
ID int AUTO_INCREMENT NOT NULL,
PLACE varchar(255) NOT NULL,
TIME int NOT NULL,
PRIMARY KEY (ID)
);